name: GitHub Python Analysis Action
run-name: ${{ github.actor }} is testing python
on: [push]

jobs:
  Python-Analysis-Actions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        ls
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python update.py > ../my_text_out.txt
        ls

    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git checkout analysis
           mv ../my_text_out.txt ./my_text_out.txt
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@analysis
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

